import Head from "next/head";
import LineChart from "@/component/LineChart";
import ActivityPerformanceOverview from "@/component/ActivityPerformanceOverview";
import BarChart from "@/component/BarChart";
import Card from "@/component/Card";
import Greeting from "@/component/Greeting";
import SearchAndNotifications from "@/component/SearchAndNotifications";
import Sidebar from "@/component/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="container">
      <Sidebar />
      <div className="main-content">
        {/* Use the new SearchAndNotifications component here */}
        <SearchAndNotifications />
        
        <div className="dashboard-content">
          <Greeting />
          {/* Cards Section */}
          <div className="cards-container">
            <Card
              icon="/Frame 2915.svg" // Path to the image in the public folder
              title="Active Users"
              value={136}
            />
            <Card
              icon="/Frame 2915 (1).svg" // Path to the image in the public folder
              title="Venues"
              value={136}
            />
            <Card
              icon="/Frame 2915 (2).svg" // Path to the image in the public folder
              title="Activities"
              value={136}
            />
          </div>
          {/* Charts Section */}
          <div className="charts-container">
            <BarChart />
            <ActivityPerformanceOverview />
          </div>
        </div>
        <LineChart />
      </div>
    </div>
    </>
  );
}
